spring.application.name=itineria
spring.datasource.url=jdbc:postgresql://localhost:5432/itineria_db
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update